config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :listings do
    resources :orders, only: [:new, :create]
  end

  resources :listings do 
    resources :reviews
  end
  
  get 'pages/about'

  get 'pages/contact'

  get 'seller' , to: 'listings#seller'
  get 'search' , to: 'listings#search'
  get 'sales' , to: 'orders#sales'
  get 'purchases', to: 'orders#purchases'

  get 'login', to: 'devise/sessions#new', as: 'login'

  root 'listings#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    
	  has_attached_file :image, styles: { medium: "800x800>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  	validates :name, :description, :price, presence: true
  	validates :price, numericality: { greater_than: 0 }
  	validates_attachment_presence :image

  	belongs_to :user
  	has_many :orders
  	has_many :reviews
  	belongs_to :category

  	def self.search(search)
  		where("name ILIKE ?", "%#{search}%") 
	end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  def seller
    @listings = Listing.where(user: current_user).order('created_at DESC')
  end

  def search
    @listings = Listing.all
    if params[:search]
      @listings = Listing.search(params[:search]).order("created_at DESC")
    else
      @listings = Listing.all.order("created_at DESC")
    end
  end
  # GET /listings
  # GET /listings.json
  def index
    redirect_to '/users/sign_in' unless user_signed_in?
    if params[:category].blank?
      @listings = Listing.all.order('created_at DESC')
    else
      @category_id = Category.find_by(name: params[:category]).id
      @listings = Listing.where(category_id: @category_id).order("created_at DESC")
    end  
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    if @listing.reviews.blank?
      @average_review = 0
    else
      @average_review = @listing.reviews.average(:rating).round(2)
    end
  end

  # GET /listings/new
  def new
    @listing = Listing.new
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # GET /listings/1/edit
  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    @listing.category_id = params[:category_id]

    Stripe.api_key = ENV['SECRET_KEY']
    token = params[:stripeToken]

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    @listing.category_id = params[:category_id]

    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.friendly.find(params[:id])

     rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The page you requested does not exist"
      redirect_to root_url
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image, :category_id)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true, html: { multipart: true }) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= select_tag(:category_id, options_for_select(@categories), prompt: 'Select Category') %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :listing_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :listing_description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :listing_price, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= form.submit class: 'btn btn-info' %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= form_with(model: @listing, local: true, html: { multipart: true }) do |form| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.select :category_id,@categories %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :listing_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :listing_description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :listing_price, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= form.submit class: 'btn btn-info' %>
  </div>
<% end %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
     
    
<h2 class="current-category"><%= params[:category] %></h2>
<% if @listings.count == 0 %>
  <h3>There are no plays in this category</h3>
<% else %> 
  <div class="center">
    <div class="row">
      <% @listings.each do |listing| %>
        <div class="col-md-3">
          <div class="thumbnail">
            <%= link_to image_tag(listing.image.url), listing %>
            <div class="caption">
              <h3><%= listing.name %></h3>
              <p><%= number_to_currency(listing.price) %></p>
              <p><%= "Sold by #{listing.user.name}" %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/search.html.erb
<% if @listings.blank? %>
  <h4>There are no  <%= params[:search] %>.</h4>
<% else %>
	<div class="center">
    <div class="row">
      <% @listings.each do |listing| %>
        <div class="col-md-3">
          <div class="thumbnail">
            <%= link_to image_tag(listing.image.url), listing %>
            <div class="caption">
              <h3><%= listing.name %></h3>
              <p><%= number_to_currency(listing.price) %></p>
              <p><%= "Sold by #{listing.user.name}" %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/listings/seller.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Description</th>
    <th class="center">Price</th>
    <th class="center">Action</th>
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td>
        <%= image_tag listing.image.url(:thumb) %>
      </td>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <td><%= number_to_currency(listing.price) %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", listing, class: "btn btn-link" %></li>
            <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
            <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-8">
      <%= image_tag @listing.image.url, class: "img-thumbnail" %>  
  </div>
  <div class="col-md-4">
    <h3><%= @listing.name %></h3>
    <p><%= number_to_currency(@listing.price) %></p>
    <h4>Subject: <%= @listing.category.name %></h4>
    <p>
      <h4 class="avg-rating">Average Rating</h4>
      <div class="average-review-rating" data-score=<%= @average_review %>></div>
      <span class="number-of-reviews">
        <em>From: </em><%= @listing.reviews.count %> reviews 
      </span>
    </p>
    <p><%= @listing.description %></p>
    <br>
    <div class="center">
      <%= link_to "Buy It Now", new_listing_order_path(@listing), class: "btn btn-primary", data: { no_turbolink: true } %>
    </div>   
  </div>
</div>

<% if (user_signed_in?) && (current_user == @listing.user) %>
 	<%= link_to 'Edit', edit_listing_path(@listing) %> |
	<%= link_to 'Delete', listing_path(@listing), method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', listings_path %> 

<div class="row">
  <div class="col-md-12">
    <div class="reviews">
      <h1> Reviews</h1>
      <%= render @listing.reviews %>
      <%= link_to 'Add Reviews', new_listing_review_path(@listing), class: 'btn btn-primary' %>
    </div>
  </div>
</div>

<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>


<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>