config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :listings do
    resources :orders, only: [:new, :create]
  end

  resources :listings do 
    resources :reviews
  end
  
  get 'pages/about'

  get 'pages/contact'

  get 'seller' , to: 'listings#seller'
  get 'search' , to: 'listings#search'
  get 'sales' , to: 'orders#sales'
  get 'purchases', to: 'orders#purchases'

  get 'login', to: 'devise/sessions#new', as: 'login'

  root 'listings#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_carousel.html.erb
<div class="row">
  <div class="col-md-8">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag "graduate.jpeg",class:"img-rounded" %>
        </div>

        <div class="item">
          <%= image_tag "library.jpeg",class:"img-rounded"  %>
        </div>
    
        <div class="item">
          <%= image_tag "science.jpeg",class:"img-rounded"  %>
        </div>
      </div>

      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  
  <ul class="mini">
    <li class="col-md-4 ">  
      <%= image_tag 'textbooks.png' %>
    </li>
    <li class="col-md-4 ">
        <%= link_to image_tag('text-book.png'), listings_path %>
    </li>
  </ul>

</div>
  

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default " role="navigation">
 
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    
    <%= link_to 'Text-Book', root_path, class: 'navbar-brand ' %>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "About", pages_about_path %></li>
      <li><%= link_to "Contact", pages_contact_path %></li>
      <li>
        <%= form_tag(search_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Text-Book",class: 'search-bar', size:"50" %>
          <%= submit_tag "Search", class: 'btn btn-success', :name => nil %>
        <% end %>
      </li>
    </ul>
     
        
     
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Subject <span class="caret"></span></a>

          <ul class="dropdown-menu" role="menu">
            <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name %>">
                <%= link_to category.name, listings_path(category: category.name) %>
              </li>
            <% end %> 
          </ul>
        </li>
        <li><%= link_to 'Listings', listings_path %></li>
        <li><%= link_to "New Listing", new_listing_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Seller Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Manage Listings", seller_path %></li>
            <li><%= link_to "Sales History", sales_path %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag avatar_url(current_user), width: 25, class: "img-circle" %><%= current_user.name %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Purchase History", purchases_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>