config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :listings do
    resources :orders, only: [:new, :create]
  end

  resources :listings do 
    resources :reviews
  end
  
  get 'pages/about'

  get 'pages/contact'

  get 'seller' , to: 'listings#seller'
  get 'search' , to: 'listings#search'
  get 'sales' , to: 'orders#sales'
  get 'purchases', to: 'orders#purchases'

  get 'login', to: 'devise/sessions#new', as: 'login'

  root 'listings#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
	validates :address, :city, :state, presence: true

	belongs_to :listing
	belongs_to :buyer, class_name: "User"
  	belongs_to :seller, class_name: "User"
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end
  

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end

 
  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user 

    @order.listing_id = @listing.id 
    @order.buyer_id = current_user.id 
    @order.seller_id = @seller.id

    Stripe.api_key = ENV['SECRET_KEY']
    token = params[:stripeToken]

    begin
      customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount => (@listing.price * 100).floor,
        :currency => "usd",
        :card => token
        )
      flash[:notice] = "Thanks for ordering"
    rescue Stripe::CardError => e 
      flash[:danger] = e.message
    end

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url}
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

 

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag @listing.image.url %>
    </div>
    <h3><%= @listing.name %></h3>
    <h4><%= number_to_currency(@listing.price) %></h4>
  </div>
  <div class="col-md-8">
    <%= form_for ([@listing, @order]) do |form| %>
      <% if order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

          <ul>
          <% order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div id="stripe_error" class="alert alert-danger" style="display:none">
        <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
      </div>

      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_field :address, id: :order_address,class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :city %>
        <%= form.text_field :city, id: :order_city,class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :state %>
        <%= form.text_field :state, id: :order_state,class: "form-control" %>
      </div>

    <div class="form-group">
        <div class="row">
          <div class="col-md-8">
            <%= label_tag :card_number, "Credit Card Number" %>
            <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => "number", class: "form-control" } %>
          </div>
          <div class="col-md-4">
            <%= label_tag :card_code, "CVC" %>
            <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => "cvc", class: "form-control" } %>
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <%= label_tag nil, "Expiration Date" %>
        <div class="row">
          <div class="col-md-3">
            <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'data-stripe' => "exp-month", class: "form-control" } %>
          </div>
          <div class="col-md-3">
            <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { :name => nil, :'data-stripe' => "exp-year", class: "form-control" } %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= form.submit "Complete Order", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<%= render 'form', order: @order %>

<%= link_to 'Back', listing_orders_path %>

app/views/orders/purchases.html.erb
<div class="center">
  <h2>Purchase History</h2>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Item</th>
    <th class="center">Price</th>
    <th class="center">Seller</th>
    <th class="center">Date Purchased</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
      <td class="center"><%= order.listing.name %></td>
      <td class="center"><%= number_to_currency(order.listing.price) %></td>
      <td class="center"><%= order.seller.name %></td>
      <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
    </tr>
  <% end %>
</table>

app/views/orders/sales.html.erb
<div class="center">
  <h2>Sales History</h2>
</div>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Item</th>
    <th class="center">Price</th>
    <th class="center">Customer</th>
    <th class="center">Date Sold</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td class="center"><%= image_tag order.listing.image.url(:thumb) %></td>
      <td class="center"><%= order.listing.name %></td>
      <td class="center"><%= number_to_currency(order.listing.price) %></td>
      <td class="center"><%= order.buyer.name %></td>
      <td class="center"><%= order.created_at.strftime("%B %-d, %Y") %></td>
    </tr>
  <% end %>
</table>