config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :listings do
    resources :orders, only: [:new, :create]
  end

  resources :listings do 
    resources :reviews
  end
  
  get 'pages/about'

  get 'pages/contact'

  get 'seller' , to: 'listings#seller'
  get 'search' , to: 'listings#search'
  get 'sales' , to: 'orders#sales'
  get 'purchases', to: 'orders#purchases'

  get 'login', to: 'devise/sessions#new', as: 'login'

  root 'listings#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_listing 
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
  	
  	@review = Review.new
  end

  def create
  	
  	@review = Review.new(review_params)
  	@review.listing_id = @listing.id 
  	@review.user_id = current_user.id 

  	if @review.save
  		redirect_to listing_path(@listing)
  	else
  		render 'new'
  	end
  end


  def edit
  	
  end

  def update
  	
  	if @review.update(review_params)
			redirect_to listing_path(@listing)
		else
			render 'edit'
		end
  end

  def destroy
  	
  	@review.destroy
	redirect_to listing_path(@listing)
  end

  private

  def review_params
  	params.require(:review).permit(:rating, :comment)
  end

  def set_listing
      @listing = Listing.find(params[:listing_id])
    end

  def find_review
  	@review = Review.find(params[:id])
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for([@listing, @listing.reviews.build]) do |f| %>
	<p>
		<div id="rating-form">
			<label> Rating </label>
		</div>
	</p>
	<p>
		 <%= f.label :review %>
		<%= f.text_area :comment %>
	</p>
   
	<%= f.submit "Create", class: 'btn btn-primary' %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p><%= review.comment %></p>

<% if user_signed_in? %>
	<% if review.user_id == current_user.id %>		
		<%= link_to "Edit", edit_listing_review_path(review.listing, review), class: "btn btn-info" %>
		<%= link_to "Delete", listing_review_path(review.listing, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>	
	<% end %>
<% end %>

app/views/reviews/edit.html.erb
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<%= form_for([@listing, @review]) do |f| %>
			<p>
				<div id="rating-form">
					<label> Rating </label>
				</div>
			</p>
			<p>
				 <%= f.label :review %>
				<%= f.text_area :comment %>
			</p>
		   
			<%= f.submit "Edit", class: 'btn btn-primary' %>
		<% end %>
	</div>
</div>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">
	<h2>Reviews</h2>
	<%= render 'form' %>
</div>